### ISSUE TITLE
Safari bug

### ISSUE THREAD

**Issue by sbesh91** [mattkrick/lolliclock#4] opened 2015-06-19 13:31 UTC
Safari still seems to not function even after yesterday's fix that allowed IE 11/10 to function.  
I've attached a screenshot of the issue right after clicking to open the time picker.
![screen shot 2015-06-19 at 8 30 06 am](https://cloud.githubusercontent.com/assets/3409138/8254376/93fd029e-165d-11e5-97ac-0cbf30263acd.png)

**Comment by mattkrick** [comment] 2015-06-19 15:06
Just tested it in safari & IE & both work for me, feel free to submit a PR if you track down the problem

**Comment by sbesh91** [comment] 2015-06-19 15:34
Would it be a problem to load this in a bootstrap modal?

**Comment by mattkrick** [comment] 2015-06-19 15:37
You can borrow the code from bootstrap, but I don't think it makes sense to
bloat it up with bootstrap just for a couple lines of css.

**Comment by Antoss** [comment] 2015-07-02 22:47
excellent plugin just that when added to a mobile application in meteor, but to test it on an iPhone in the section where the hour and minute NaN NaN sends me appear .
Not if they had any solution.

**Comment by mattkrick** [comment] 2015-07-06 18:53
does it happen on the emulator, or just the iphone? this should've been fixed with the latest version, the problem is safari doesn't follow ES5 date formats, so the parsing gets messed up.

**Closed as completed** 2021-09-03 19:44 UTC
